export enum Combat {
  Adrenaline = 'Adrenaline',
  AllOutAttack = 'All Out Attack',
  AmbushMaster = 'Ambush Master',
  Awakening = 'Awakening',
  Barricade = 'Barricade',
  BrokenBone = 'Broken Bone',
  Contender = 'Contender',
  CrisisEvasion = 'Crisis Evasion',
  CrushingFist = 'Crushing Fist',
  CursedDoll = 'Cursed Doll',
  Disrespect = 'Disrespect',
  DivineProtection = 'Divine Protection',
  DropsofEther = 'Drops of Ether',
  EmergencyRescue = 'Emergency Rescue',
  EnhancedShield = 'Enhanced Shield',
  EtherPredator = 'Ether Predator',
  Expert = 'Expert',
  ExplosiveExpert = 'Explosive Expert',
  Fortitude = 'Fortitude',
  Grudge = 'Grudge',
  HeavyArmor = 'Heavy Armor',
  HitMaster = 'Hit Master',
  KeenBluntWeapon = 'Keen Blunt Weapon',
  LightningFury = 'Lightning Fury',
  MagickStream = 'Magick Stream',
  MassIncrease = 'Mass Increase',
  MasterBrawler = 'Master Brawler',
  MasterofEscape = 'Master of Escape',
  MastersTenacity = 'Master\'s Tenacity',
  MaxMPIncrease = 'Max MP Increase',
  MPEfficiencyIncrease = 'MP Efficiency Increase',
  Necromancy = 'Necromancy',
  PreciseDagger = 'Precise Dagger',
  PreemptiveStrike = 'Preemptive Strike',
  Propulsion = 'Propulsion',
  RaidCaptain = 'Raid Captain',
  ShieldPiercing = 'Shield Piercing',
  SightFocus = 'Sight Focus',
  SpiritAbsorption = 'Spirit Absorption',
  StabilizedStatus = 'Stabilized Status',
  StrongWill = 'Strong Will',
  SuperCharge = 'Super Charge',
  VitalPointHit = 'Vital Point Hit',
}

export enum Class {
ArthetineanSkill = 'Arthetinean Skill',
BarrageEnhancement = 'Barrage Enhancement',
BerserkersTechnique = 'Berserker\'s Technique',
BlessedAura = 'Blessed Aura',
CombatReadiness = 'Combat Readiness',
CommunicationOverflow = 'Communication Overflow',
Control = 'Control',
DeathStrike = 'Death Strike',
Deathblow = 'Deathblow',
DemonicImpulse = 'Demonic Impulse',
DesperateSalvation = 'Desperate Salvation',
EmpresssGrace = 'Empress\'s Grace',
EnergyOverflow = 'Energy Overflow',
EnhancedWeapon = 'Enhanced Weapon',
EsotericFlurry = 'Esoteric Flurry',
EsotericSkillEnhancement = 'Esoteric Skill Enhancement',
EvolutionaryLegacy = 'Evolutionary Legacy',
FirepowerEnhancement = 'Firepower Enhancement',
FirstIntention = 'First Intention',
FullBloom = 'Full Bloom',
GravityTraining = 'Gravity Training',
Hunger = 'Hunger',
Igniter = 'Igniter',
Judgment = 'Judgment',
LoneKnight = 'Lone Knight',
LoyalCompanion = 'Loyal Companion',
LunarVoice = 'Lunar Voice',
MasterSummoner = 'Master Summoner',
Mayhem = 'Mayhem',
OrderoftheEmperor = 'Order of the Emperor',
Peacemaker = 'Peacemaker',
PerfectSuppression = 'Perfect Suppression',
Pinnacle = 'Pinnacle',
Pistoleer = 'Pistoleer',
Predator = 'Predator',
Punisher = 'Punisher',
RageHammer = 'Rage Hammer',
Recurrence = 'Recurrence',
Reflux = 'Reflux',
RemainingEnergy = 'Remaining Energy',
RobustSpirit = 'Robust Spirit',
ShockTraining = 'Shock Training',
Surge = 'Surge',
TimetoHunt = 'Time to Hunt',
TrueCourage = 'True Courage',
UltimateSkillTaijutsu = 'Ultimate Skill: Taijutsu',
}

export const EngravingValues = {
  Adrenaline: {
    description: 'After using skills (excluding movement skills and basic attacks), gains +0.3% / 0.6% / 1% Atk. Power for 6 seconds, stacking up to 6 times, up to a maximum of 1.8% / 3.6% / 6% Atk. Power. At maximum stacks, Crit Rate +5% / 10% / 15%. If Cooldown reduction due to skill cancel is applied to this effect, it is applied after the end of the skill.',
    img: '',
  }
}