export enum Combat {
  'Adrenaline' = 'Adrenaline',
  'All Out Attack' = 'All Out Attack',
  'Ambush Master' = 'Ambush Master',
  'Awakening' = 'Awakening',
  'Barricade' = 'Barricade',
  'Broken Bone' = 'Broken Bone',
  'Contender' = 'Contender',
  'Crisis Evasion' = 'Crisis Evasion',
  'Crushing Fist' = 'Crushing Fist',
  'Cursed Doll' = 'Cursed Doll',
  'Disrespect' = 'Disrespect',
  'Divine Protection' = 'Divine Protection',
  'Drops of Ether' = 'Drops of Ether',
  'Emergency Rescue' = 'Emergency Rescue',
  'Enhanced Shield' = 'Enhanced Shield',
  'Ether Predator' = 'Ether Predator',
  'Expert' = 'Expert',
  'Explosive Expert' = 'Explosive Expert',
  'Fortitude' = 'Fortitude',
  'Grudge' = 'Grudge',
  'Heavy Armor' = 'Heavy Armor',
  'Hit Master' = 'Hit Master',
  'Keen Blunt Weapon' = 'Keen Blunt Weapon',
  'Lightning Fury' = 'Lightning Fury',
  'Magick Stream' = 'Magick Stream',
  'Mass Increase' = 'Mass Increase',
  'Master Brawler' = 'Master Brawler',
  'Master of Escape' = 'Master of Escape',
  "Master's Tenacity" = "Master's Tenacity",
  'Max MP Increase' = 'Max MP Increase',
  'MP Efficiency Increase' = 'MP Efficiency Increase',
  'Necromancy' = 'Necromancy',
  'Precise Dagger' = 'Precise Dagger',
  'Preemptive Strike' = 'Preemptive Strike',
  'Propulsion' = 'Propulsion',
  'Raid Captain' = 'Raid Captain',
  'Shield Piercing' = 'Shield Piercing',
  'Sight Focus' = 'Sight Focus',
  'Spirit Absorption' = 'Spirit Absorption',
  'Stabilized Status' = 'Stabilized Status',
  'Strong Will' = 'Strong Will',
  'Super Charge' = 'Super Charge',
  'Vital Point Hit' = 'Vital Point Hit',
}

export enum Class {
  'Arthetinean Skill' = 'Arthetinean Skill',
  'Barrage Enhancement' = 'Barrage Enhancement',
  "Berserker's Technique" = "Berserker's Technique",
  'Blessed Aura' = 'Blessed Aura',
  'Combat Readiness' = 'Combat Readiness',
  'Communication Overflow' = 'Communication Overflow',
  'Control' = 'Control',
  'Death Strike' = 'Death Strike',
  'Deathblow' = 'Deathblow',
  'Demonic Impulse' = 'Demonic Impulse',
  'Desperate Salvation' = 'Desperate Salvation',
  'Empresss Grace' = "Empress's Grace",
  'Energy Overflow' = 'Energy Overflow',
  'Enhanced Weapon' = 'Enhanced Weapon',
  'Esoteric Flurry' = 'Esoteric Flurry',
  'Esoteric Skill Enhancement' = 'Esoteric Skill Enhancement',
  'Evolutionary Legacy' = 'Evolutionary Legacy',
  'Firepower Enhancement' = 'Firepower Enhancement',
  'First Intention' = 'First Intention',
  'Full Bloom' = 'Full Bloom',
  'Gravity Training' = 'Gravity Training',
  'Hunger' = 'Hunger',
  'Igniter' = 'Igniter',
  'Judgment' = 'Judgment',
  'Lone Knight' = 'Lone Knight',
  'Loyal Companion' = 'Loyal Companion',
  'Lunar Voice' = 'Lunar Voice',
  'Master Summoner' = 'Master Summoner',
  'Mayhem' = 'Mayhem',
  'Order of the Emperor' = 'Order of the Emperor',
  'Peacemaker' = 'Peacemaker',
  'Perfect Suppression' = 'Perfect Suppression',
  'Pinnacle' = 'Pinnacle',
  'Pistoleer' = 'Pistoleer',
  'Predator' = 'Predator',
  'Punisher' = 'Punisher',
  'Rage Hammer' = 'Rage Hammer',
  'Recurrence' = 'Recurrence',
  'Reflux' = 'Reflux',
  'Remaining Energy' = 'Remaining Energy',
  'Robust Spirit' = 'Robust Spirit',
  'Shock Training' = 'Shock Training',
  'Surge' = 'Surge',
  'Time to Hunt' = 'Time to Hunt',
  'True Courage' = 'True Courage',
  'Ultimate Skill: Taijutsu' = 'Ultimate Skill: Taijutsu',
}

export const EngravingValues = {
  Adrenaline: {
    description:
      'After using skills (excluding movement skills and basic attacks), gains +0.3% / 0.6% / 1% Atk. Power for 6 seconds, stacking up to 6 times, up to a maximum of 1.8% / 3.6% / 6% Atk. Power. At maximum stacks, Crit Rate +5% / 10% / 15%. If Cooldown reduction due to skill cancel is applied to this effect, it is applied after the end of the skill.',
    img: '',
  },
};
